= csoftz-polarbookstore-catalog-service

Standalone repository for the _'catalog-service_'.
Keeps the same code as Thomas Vitale Book Spring Cloud Native but in my own format.
He uses Gradle in the _git_ repository, but I use Maven instead.

The book reference follows:
https://www.manning.com/books/cloud-native-spring-in-action[Cloud Native Spring in Action^] book by https://www.thomasvitale.com[Thomas Vitale^].

Provides functionality for managing the books in the catalog.

== REST API

[%header]
|===
|Endpoint|Method|Req. body|Status|Resp. body|Description
| /api/v1/books        | GET    |            | 200 | Book[] | Get all the books in the catalog
| /api/v1/books        | POST   | Book       | 201 | Book   | Add a new book to the catalog.
|                      |        |            | 422 |        | A book with the same ISBN already exists.
| /api/v1/books/{isbn} | GET    |            | 200 | Book   | Get the book with the given ISBN.
|                      |        |            | 404 |        | No book with the given ISBN exists.
| /api/v1/books/{isbn} | PUT    | Book       | 200 | Book   | Update the book with the given ISBN.
|                      |        |            | 201 | Book   | Create a book with the given ISBN.
| /api/v1/books/{isbn} | DELETE |            | 204 |        | Delete the book with the given ISBN.
|===

[source,bash]
----
$ mvn spring-boot:buildImage <1>
$./gradlew bootBuildImage <2>
----
<1> Maven (Uses Buildpacks to generate the Docker image)
<2> Gradle (Uses Buildpacks to generate the Docker image)

[source,bash]
----
$ mvn -Pnative spring-boot:build-image <1>
$./gradlew bootBuildImage <2>
----
<1> Maven (Uses Buildpacks and GraalVM to generate the Docker image)
<2> Gradle (Uses Buildpacks and GraalVM to generate the Docker image)

[source,bash]
----
$ docker run --rm --name catalog-service -p 8080:8080 catalog-service:2023.1.0
----

To run the _Kubernetes_ commands, it is required that you have a local development cluster, here we use
*_Rancher Desktop_*.

[source,bash]
----
$ kubectl create deployment catalog-service --image=catalog-service:2023.1.0
----

You can verify the creation of the Deployment object as follows:

[source,bash]
----
$ kubectl get deployment
----

To check pods

[source,bash]
----
$ kubectl get pod
----

You can check the application logs by running

[source,bash]
----
$ kubectl logs deployment/catalog-service
----

By default, applications running in _Kubernetes_ are not accessible.
To enable it, run the following command.

[NOTE]
====
The Catalog Service is listening in port 8080, so to expose the deployment service with the following command you use 8080 port.
====

[source,bash]
----
$ kubectl expose deployment catalog-service --name=catalog-service --port=8080
----

To verify the service is exposed.

[source,bash]
----
$ kubectl get service catalog-service
----

Last thing to do is forward the traffic to the service.

[source,bash]
----
$ kubectl port-forward service/catalog-service 8000:8080
----

Now if you need to remove everything so far.

[source,bash]
----
$ kubectl delete deployment catalog-service
----

[source,bash]
----
$ kubectl delete service catalog-service
----

Now to check that the service is running as expected, use the following cURL/HTTPie.

[source,bash]
----
$ curl --request GET --url http://127.0.0.1:8000/api/v1/home
$ http GET http://127.0.0.1:8000/api/v1/home
----

== Local Development

When you run it locally, and you enable the *_Spring Boot_* profile named _'testdata'_
then it will populate the Book database table with some test data.
This profile must not be activated for other environments or even in local development should you need empty data or existing data.

To activate the profile you can include the following entry as an Environment key.

[source,bash]
----
ENV spring.profiles.active=testdata --> this needs to be rewritten to put the correct information.
----

== Dockerized app

[source,bash]
----
$ docker network create [network name]
----

== Integrating with a Data Service Using PostgreSQL

In order to connect to a *_PostgreSQL_* Database, we use *_Docker_* for that purpose.
Use the following command.

[source,bash]
----
$ docker run -d \
--name polar-postgres \
-e POSTGRES_USER=user \
-e POSTGRES_PASSWORD=password \
-e POSTGRES_DB=polardb_catalog \
-p 5432:5432 \
postgres:16.0  <1>
----

Uset the following command if you want this container to be part of a *_Docker Network_*.

[source,bash]
----
$ docker run -d \
--name polar-postgres \
--net catalog-network \ <1>
-e POSTGRES_USER=user \
-e POSTGRES_PASSWORD=password \
-e POSTGRES_DB=polardb_catalog \
-p 5432:5432 \
postgres:16.0  <1>
----

<1> https://hub.docker.com/postgres, use latest tag to use the most recent version.

[WARNING]
====
The latter command will not define a storage volume for externalizing the data the container uses, thus, when you shut down the container, the data is lost.

-> Pending to add instructions to add a docker volumen to persist data to disk.

====

[NOTE]
====
If you need to, you can stop the container with *_docker stop polar-postgres_*
and start it again with *_docker start polar-postgres_*.
If you want to start over, you can remove the container with *_docker rm -fv polar-postgres_*
and create it again with the previous docker run command.
====

== Running in a container

[source,bash]
----
$ docker run -d \
--name catalog-service \
--net catalog-network \
-p 9001:9001 \
-e SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog \
-e SPRING_PROFILES_ACTIVE=testdata \
catalog-service:2023.1.0
----

== Cleaning up

At this point you have the following elements necessary the application.

. A *_Docker_* network to communicate *_Docker_* containers.
. A PostgreSQL container named _polar-postgres_.
. The _catalog-service_ container.

This is a way of running your containerized application, somehow there is another method which
includes the use of *_Docker Compose_* componet (next section)
To clean up, type the following commands

[source,bash]
----
$ docker stop catalog-service polar-postgres <1>
$ docker container rm -fv catalog-service polar-postgres <2>
$ docker network rm catalog-network <3>
----
<1> Stop containers if they are running.
<2> Remove the container definitions.
<3> Remove the *_Docker_* Network for container communication.

== Build Docker image

Here, we use the built-in *Spring Boot* image builder via BuildPacks.
Use the following command to create the *_Docker_* image.

[source,bash]
----
$ ./mvnw spring-boot:build-image
----

When running this command, the given image name is taken from the *_Maven Spring Boot Plugin_*, but if
you would like to override it, then use the following command.

[source,bash]
----
$ ./mvnw spring-boot:build-image -Ddocker.image.name={override name}
----

== Running using Docker Compose

Open a terminal window where your _'docker-compose.yml'_ resides and execute the following command.

[source,bash]
----
$ docker-compose up -d <1>
----
<1> Run it in detached mode.

When you are done, you can remove the containers with the following command.

[source,bash]
----
$ docker-compose down
----

== Running in Kubernetes (k8s)

Open a terminal and navigate to the project root directory and type the following command to create the *Deployment*
object for *k8s*.

[source,bash]
====
$ kubectl apply -f k8s/deployment.yml
====

If everything works as expected the message should read as _'deployment.apps/catalog-service created'_.

You can verify which objects have been created with the following command:

[source,bash]
----
$ kubectl get all -l app=catalog-service
----

Now to validate that the *_catalog-service_* is running, check the logs

[source,bash]
----
$ kubectl logs deployment/catalog-service
----

Now we need a way to expose the application, and it is done by apply the following manifest to *_k8s_*.

[source,bash]
----
$ kubectl apply -f k8s/service.yml
----

The *_k8s*_ CLI says _'service/catalog-service created'_.

To verify that it was created type.

[source,bash]
----
$ kubectl get svc -l app=catalog-service
----

To expose to your local machine use the port forwarding in *_k8s_*.

[source,bash]
----
$ kubectl port-forward service/catalog-service 9002:9001
----

== Validating k8s manifests
In order to check that the manifests for *_k8s_* are compliant with the *_k8s_* API specification, use
https://www.kubeval.com/[Kubeval^].

[source,bash]
----
$ kubeval --strict -d k8s <1>
----
<1> Open a terminal to the root of project, as it will scan the _'k8s'_ folder.

=== Database commands

You can use any IDE to access the database contents such as https://dbeaver.io/[DBeaver Community - Universal Database Tool^], or you could open a terminal window connecting the Docker container.

Start an interactive PSQL console:

[source,bash]
----
$ docker exec -it polar-postgres psql -U user -d polardb_catalog
----

Then use any of the following commands to check.

[%header]
|===
| PSQL Command            | Description
| \list                    | List all databases.
| \connect polardb_catalog | Connect to specific database.
| \dt                      | List all tables.
| \d book                   | Show the *book* table schema.
| \d flyway_schema_history | Show the *flyway_schema_history* table schema.
| \quit                    | Quit interactive psql console.
|===

From within the PSQL console, you can also fetch all the data stored in the `book` table.

[source,sql]
----
select * from book;
----

The following query is to fetch all the data stored in the `flyway_schema_history` table.

[source,sql]
----
select * from flyway_schema_history;
----

== Tilt

This allows to automate the development process to run everything inside a *_k8s_* local cluster. You can go to
https://tilt.dev/[Tilt^] for set up guidelines.

After you have this app installed, go to a terminal window and type

[source, bash]
----
$ tilt up <1>
----
<1> Uses the 'Tiltfile' in the root folder to configure everything.

Once it is up and running, open _'http://localhost:10350/'_ which will show the status of the deployment.
This will monitor for updates in source folder to update environemnt. To finish working with a session, type
'CTRL+C' (Win) or '^C' (Mac), this will stop the running process.

*_Tilt_* is smart enough to know that the *_k8s_* resources are still running, in fact, it has not been instructed
to stop *_k8s_* resources, which you can do using the following command.

[source,bash]
----
$ tilt down
----

== NOTES

- Catalog Service uses the *_Spring Boot_* *_`server.shutdown=graceful`_* feature. See *_application.yml_*

