server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      # Max and Min Spare here are for local development.200 for max is the default.
      max: 50
      min-spare: 5
    